# Generated by Django 3.2.3 on 2021-06-12 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210611_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone')),
                ('comment', models.TextField(verbose_name='comment')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.blogmodel', verbose_name='comments')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'commets',
            },
        ),
    ]
